### ISSUE TITLE
Missing target heading “API”.

### ISSUE THREAD

**Issue by Laptopmini** [jaydenseric/jsdoc-md#17]
No matter what `-t` value I give, or even if I `touch API` (with a single line of markdown or not), I cannot get passed this error.

```
Error: Missing target heading “API”.
    at /Users/path-to-script/node_modules/jsdoc-md/lib/remarkPluginReplaceSection.js:23:12
    at wrapped (/Users/path-to-script/node_modules/trough/wrap.js:25:19)
    at next (/Users/path-to-script/node_modules/trough/index.js:58:24)
    at Object.run (/Users/path-to-script/node_modules/trough/index.js:32:10)
    at executor (/Users/path-to-script/node_modules/unified/index.js:295:20)
    at Function.run (/Users/path-to-script/node_modules/unified/index.js:292:5)
    at pipelineRun (/Users/path-to-script/node_modules/unified/index.js:27:5)
    at wrapped (/Users/path-to-script/node_modules/trough/wrap.js:25:19)
    at next (/Users/path-to-script/node_modules/trough/index.js:58:24)
    at done (/Users/path-to-script/node_modules/trough/wrap.js:56:16)
```

**Comment by jaydenseric** [comment]
I can't reproduce this issue. For me, on the latest version, all these variation work:

```
jsdoc-md -t API
jsdoc-md -t=API
jsdoc-md -t='API'
jsdoc-md -t="API"
```

We can reopen if you discover a way it can be reproduced 🙏
